- name : Playbook_test
  hosts: node1
  remote_user: vagrant
  tasks:
  - name: vider repo
    shell: "rm /home/vagrant/MyAppFlask -rf"
    becom: 'yes'
  - name: clone git
    git:
      repo: https://github.com/ZhiruC/MyAppFlask.git
      dest: /home/vagrant/MyAppFlask
      version: main
      clone: yes
      update: no
  - name: docker compose
    shell: "cd MyAppFlask; docker compose down; dockr compose up -d"
